# envsubst < config.toml.in > config.toml
#log-level='DEBUG'
relay=true
store=false
filter=true
lightpush=true
rln-relay=false
relay-peer-exchange=true
rest=true
rest-address='0.0.0.0'
rest-port=8546
rest-admin=true
#rest-private=true
rest-relay-cache-capacity=3000
keep-alive=false
staticnode=[]
dns-discovery=true
dns-discovery-url="enrtree://AIRVQ5DDA4FFWLRBCHJWUWOO6X6S4ZTZ5B667LQ6AJU6PEYDLRD5O@sandbox.waku.nodes.status.im"
discv5-discovery=true
discv5-bootstrap-node=[]
shard=[0, 1, 2, 3, 4, 5]
max-msg-size="512KiB"

cluster-id=0 # needed when switch to 0.33 nwaku, pubsub-topic is deprecated
filter-subscription-timeout=3000
filter-max-peers-to-serve=10000
reliability=false
num-shards-in-network=6

peer-store-capacity=500
max-connections=500
max-relay-peers=500
ip-colocation-limit=100
peer-persistence=false
